# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication
from PyQt5.QtGui import QColor, QPalette


class Ui_MainWindow(object):
    def __init__(self):
        pass

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 202)
        # 背景色1
        MainWindow.setStyleSheet("background-color: rgba(60, 60, 60)")
        # 背景色2
        # palette = QPalette()
        # palette.setColor(QPalette.Background, QColor(0, 0, 0, 143))
        # MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        # 最外层layout
        self.outerBox = QtWidgets.QVBoxLayout()
        self.outerBox.setSpacing(2)
        self.outerBox.setObjectName("outer_box")
        # 自定义工具栏
        self.toolBox = QtWidgets.QHBoxLayout()
        self.toolBox.setContentsMargins(6, 2, -1, 2)
        self.toolBox.setSpacing(0)
        self.toolBox.setObjectName("tool_box")
        # 自定义工具栏 --关闭按钮
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setObjectName("closeButton")
        self.closeButton.clicked.connect(lambda: QCoreApplication.instance().quit())
        self.closeButton.setStyleSheet("color: #eee; font-family: Microsoft YaHei UI, serif; font-size: 7pt;")
        self.toolBox.addWidget(self.closeButton)
        # 自定义工具栏 --最小化按钮
        self.minimizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.minimizeButton.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        self.minimizeButton.setFont(font)
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.clicked.connect(MainWindow.showMinimized)
        self.minimizeButton.setObjectName("pushButton_4")
        self.minimizeButton.setStyleSheet("color: #eee; font-family: Microsoft YaHei UI, serif; font-size: 7pt;")
        self.toolBox.addWidget(self.minimizeButton)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolBox.addItem(spacerItem)
        # 自定义工具栏 --透明度
        self.opacityLabel = QtWidgets.QLabel(self.centralwidget)
        self.opacityLabel.setObjectName("opacity_label")
        self.opacityLabel.setStyleSheet("color: #bbb; font-family: Microsoft YaHei UI, serif; font-size: 8pt;")
        self.toolBox.addWidget(self.opacityLabel)
        self.opacityLabelSlider = QtWidgets.QSlider(self.centralwidget)
        self.opacityLabelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.opacityLabelSlider.setObjectName("opacity_label_slider")
        self.toolBox.addWidget(self.opacityLabelSlider)
        self.toolBox.addItem(spacerItem)
        # 自定义工具栏 --选择文件夹
        self.txtDirButton = QtWidgets.QPushButton(self.centralwidget)
        self.txtDirButton.setMaximumSize(QtCore.QSize(24, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.txtDirButton.setFont(font)
        self.txtDirButton.setObjectName("txt_dir_button")
        self.txtDirButton.setStyleSheet("color: #eee; font-family: Microsoft YaHei UI, serif; font-size: 6pt;")
        self.txtDirButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBox.addWidget(self.txtDirButton)
        # 自定义工具栏 --刷新文件夹
        self.txtDirFlush = QtWidgets.QPushButton(self.centralwidget)
        self.txtDirFlush.setMaximumSize(QtCore.QSize(17, 17))
        font = QtGui.QFont()
        self.txtDirFlush.setFont(font)
        self.txtDirFlush.setObjectName("txt_dir_flush")
        self.txtDirFlush.setStyleSheet("color: #eee; font-family: Microsoft YaHei UI, serif; font-size: 6pt;")
        self.txtDirFlush.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBox.addWidget(self.txtDirFlush)
        self.toolBox.addItem(spacerItem)
        self.toolBox.addStretch(1)
        # 自定义工具栏 --结束
        self.outerBox.addLayout(self.toolBox)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.outerBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        """
        设置窗体文本
        :param MainWindow:
        :return:
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.opacityLabel.setText(_translate("MainWindow", "透明度"))
        self.txtDirButton.setText(_translate("MainWindow", "Dir"))
        self.txtDirFlush.setText(_translate("MainWindow", "R"))
        self.minimizeButton.setText(_translate("MainWindow", "-"))
        self.closeButton.setText('x')

